#!/usr/bin/env bash

set -x

# ====== Variables =============================

declare -A gaps
declare -A color

gaps["top"]="5"
gaps["bottom"]="5"
gaps["left"]="5"
gaps["right"]="5"
gaps["inner"]="10"

# Uncomment to refresh ubersicht widget on workspace change
# Make sure to replace WIDGET NAME for the name of the ubersicht widget
#ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"WIDGET NAME\"'"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ===== Tiling setting =========================

yabai -m config layout                      bsp

yabai -m config split_ratio                 0.50
yabai -m split_type                         auto
yabai -m auto_balance                       off

yabai -m config top_padding                 "${gaps["top"]}"
yabai -m config bottom_padding              "${gaps["bottom"]}"
yabai -m config left_padding                "${gaps["left"]}"
yabai -m config right_padding               "${gaps["right"]}"
yabai -m config window_gap                  "${gaps["inner"]}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         on

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config window_border               on
yabai -m config window_border_width         2
yabai -m config window_border_radius        12
yabai -m config window_border_blur          on
yabai -m config window_border_hidpi         on
yabai -m config active_window_border_color  "0xff6b81ce"
yabai -m config normal_window_border_color  "0xff4b588a"
yabai -m config insert_feedback_color       "0xff6c5ce7"

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90
yabai -m config split_ratio                 0.50

yabai -m config auto_balance                on

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

# Rules
yabai -m rule --add app="kitty" manage=off
yabai -m rule --add app="^Transmit" manage=off
yabai -m rule --add app="^访达$" manage=off
yabai -m rule --add app="^关于本机$" manage=off
yabai -m rule --add app="网易有道词典" manage=off
yabai -m rule --add app="^系统偏好设置$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add app="^(Calculator|System Preferences|Archive Utility)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off

# Space labels
yabai -m space 1 --label "web"
yabai -m space 2 --label "work"
yabai -m space 3 --label "code"
yabai -m space 4 --label "dev"
yabai -m space 5 --label "misc"

# Space config
yabai -m config --space 3 layout stack
yabai -m config --space 5 layout float

# Internet
yabai -m rule --add app="Chrome"                space=1
yabai -m rule --add app="Safari"                space=1

# Work
yabai -m rule --add app="WPS"                   space=2
yabai -m rule --add app="Apifox"                space=2
yabai -m rule --add app="Typora"                space=2
yabai -m rule --add app="Postman"               space=2
yabai -m rule --add app="PDF Expert"            space=2
yabai -m rule --add app="TeamViewer"            space=2
yabai -m rule --add app="Microsoft Word"        space=2
yabai -m rule --add app="Microsoft Excel"       space=2
yabai -m rule --add app="Microsoft PowerPoint"  space=2

# Code
yabai -m rule --add app="WebStorm"              space=3
yabai -m rule --add app="PyCharm CE"            space=3
yabai -m rule --add app="IntelliJ IDEA"         space=3
yabai -m rule --add app="IntelliJ IDEA CE"      space=3

# Dev
yabai -m rule --add app="draw.io"               space=4
yabai -m rule --add app="TablePlus"             space=4
yabai -m rule --add app="Sequel Ace"            space=4
yabai -m rule --add app="Navicat Premium"       space=4
yabai -m rule --add app="Visual Studio Code"    space=4

# Chat
yabai -m rule --add app="QQ"                    space=5
yabai -m rule --add app="IINA"                  space=5
yabai -m rule --add app="Music"                 space=5
yabai -m rule --add app="WeChat"                space=5
yabai -m rule --add app="ScreenFlow"            space=5
yabai -m rule --add app="QuickTime Player"      space=5

set +x
printf "yabai: configuration loaded...\\n"
